name: Draft box
favicon: null
layout_spectrum: 0.7252765863668174
typography_spectrum: 0.7318871461320668
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.8617569452617317
  lightness: 0.6506871655583382
  saturation: 0.007257641758769751
  rhythmicContrast: 0.859107741387561
purpose: []
