name: Draft box
favicon: null
layout_spectrum: 0.25384
typography_spectrum: 0.7318871461320668
title: Draft box
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#95d2ff'
    - '#07100f'
    - '#4b4b27'
    - '#859c66'
    - '#e5eb89'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
