typography_spectrum: 0
color:
  brandColors:
    - '#95d2ff'
    - '#07100f'
    - '#4b4b27'
    - '#859c66'
    - '#e5eb89'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.25384
analytics:
  google: null
  facebook: null
  twitter: null
name: Draft box
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Growers Land
    url: 'http://growers.land'
    type: external
favicon: null
title: Draft box
purpose: []
